#!/usr/bin/env ruby
require 'ripper'
require 'fileutils'

help = <<TEXT
Usage: brew install-path [-h|--help] [-v|--version] [--cask|--formula] [OTHER_OPTIONS]... [--] <PATH>...

Options:
  -h, --help               Print this help and exit
  -v, --version            Print version and exit
  --cask                   Treat all named arguments as casks
  --formula, --formulae    Treat all named arguments as formulas

All other options are forwarded to 'brew install'
TEXT

treat_all_as_cask = false
treat_all_as_formula = false
paths = []
$forwarded_options = []
index = 0
while index < ARGV.size
  current = ARGV[index]
  if current == '--'
    index += 1
    paths += ARGV[index..]
    break
  elsif current == '-h' || current == '--help'
    puts help
    exit
  elsif current == '-v' || current == '--version'
    puts "1.1.0"
    exit
  elsif current == '--cask'
    treat_all_as_cask = true
    index += 1
  elsif current == '--formula' || current == '--formulae'
    treat_all_as_formula = true
    index += 1
  elsif current.start_with?('./') || current.start_with?('../') || current.start_with?('/') || current.end_with?('.rb')
    paths += [current]
    index += 1
  else
    $forwarded_options += [current]
    index += 1
  end
end

if treat_all_as_formula && treat_all_as_cask
  STDERR.puts "--cask and --formula are conflicting options"
  exit 1
end

if paths.empty?
  STDERR.puts "Error: At least one PATH is required"
  STDERR.puts help
  exit 1
end

def is_cask(file_path)
  code = File.read(file_path)
  tokens = Ripper.lex(code)

  tokens.each do |(_, type, token, _)|
    # Skip comments, newlines, and whitespace
    if type == :on_comment || type == :on_sp || type == :on_ignored_nl || type == :on_embdoc_beg || type == :on_embdoc || type == :on_embdoc_end
      next
    end

    return token == 'cask'
  end

  return false
end

def copy_create_parent_dirs(src, dst)
  FileUtils.mkdir_p(File.dirname(dst))
  FileUtils.cp(src, dst)
end

def my_system(*args)
  ret = system(*args)
  exit $?.exitstatus unless $?.success?
  ret
end

$brew_prefix = `brew --prefix`.chomp

def install_cask(path, filename, package_name)
  copy_create_parent_dirs(path, "#{$brew_prefix}/Library/Taps/nikitabobko/homebrew-local-tap/Casks/#{filename}")
  my_system('brew', 'install', '--cask', *$forwarded_options, "nikitabobko/local-tap/#{package_name}")
end

def install_formula(path, filename, package_name)
  copy_create_parent_dirs(path, "#{$brew_prefix}/Library/Taps/nikitabobko/homebrew-local-tap/Formula/#{filename}")
  my_system('brew', 'install', '--formula', *$forwarded_options, "nikitabobko/local-tap/#{package_name}")
end

paths.each do |path|
  package_name = File.basename(path, '.rb')
  filename = File.basename(path)
  if treat_all_as_cask
    install_cask(path, filename, package_name)
  elsif treat_all_as_formula
    install_formula(path, filename, package_name)
  elsif is_cask(path)
    install_cask(path, filename, package_name)
  else
    install_formula(path, filename, package_name)
  end
end
